### ISSUE TITLE
[code quality] Useless variable tag_dictionary

### ISSUE THREAD

**Issue by ilyash-b** [aws-samples/resource-auto-tagger#10]
https://github.com/aws-samples/resource-auto-tagger/blob/8b7f0f5acb6905536dd2e24cc692db11ae970bfa/source/resource-auto-tagger.py#L54-L58

How about instead of

```
                tag_dictionary = dict()
                path_components = parameter['Name'].split("/")
                tag_key = path_components[-1]
                tag_dictionary['Key'] = tag_key
                tag_dictionary['Value'] = parameter['Value']
                tag_list.append(tag_dictionary)
```

have

```
                path_components = parameter['Name'].split("/")
                tag_key = path_components[-1]
                tag_list.append({'Key': tag_key, 'Value': parameter['Value']})
```

(untested)

**Comment by billdry** [comment]
Hi ilyash-b,

Thank you for your feedback and improvement example.  We are reviewing the issue & will address it.

**Comment by billdry** [comment]
tag_dictionary was removed in the latest commit.  Tag key:value pairs are now formatted into python dictionaries and appended to the tag list in the latest commit.

**Comment by billdry** [comment]
I made the fix described in my previous comment on this issue, made the commit to this repo & will now close this issue.
