### ISSUE TITLE
Was code review done?

### ISSUE THREAD

**Issue by ilyash-b** [aws-samples/resource-auto-tagger#12]
I was looking at this repository because it was linked from https://aws.amazon.com/blogs/mt/auto-tag-aws-resources/ .

Multiple code quality issues (I've just opened 11 issues) made me wonder about the process. Was this code reviewed by someone?

**Comment by ilyash-b** [comment]
In general, code linked from AWS blogs - is it being reviewed?

**Comment by ACannuniRP** [comment]
Sincerely, having tested the code, I believe that this code has never been deployed at all.

**Comment by billdry** [comment]
Hello,

Sorry you are experiencing the issues raised against this script.  We are reviewing all the issues and will issue fixes for them.

**Comment by ilyash** [comment]
Related: https://github.com/awslabs/tag-tamer/issues/4

**Comment by billdry** [comment]
All issues raised were addressed in latest commit.
