### ISSUE TITLE
[Bug] free variable 'resource_id' referenced before assignment in enclosing scope

### ISSUE THREAD

**Issue by ACannuniRP** [aws-samples/resource-auto-tagger#14]
The variable `resource_id` is used inside `get_role_tags` when an exception occurs but the value is not set inside the function nor passed to the function.
When no role tags are defined the following error is presented:
```
{
  "errorMessage": "free variable 'resource_id' referenced before assignment in enclosing scope",
  "errorType": "NameError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 123, in lambda_handler\n    resource_role_tags = get_role_tags(role_name)\n",
    "  File \"/var/task/lambda_function.py\", line 36, in get_role_tags\n    print(\"No Tags Applied To: \", resource_id)\n"
  ]
}
```

**Comment by billdry** [comment]
Hi,

Thank you for your feedback. We are reviewing your issue when no tags are assigned to an IAM role and will fix it.

**Comment by billdry** [comment]
Now checks for IAM rrole tags if passed AWS CloudTrail event contains an AssumedRole type.
