### ISSUE TITLE
[code quality] Meaningless comment

### ISSUE THREAD

**Issue by ilyash-b** [aws-samples/resource-auto-tagger#2]
https://github.com/aws-samples/resource-auto-tagger/blob/8b7f0f5acb6905536dd2e24cc692db11ae970bfa/source/resource-auto-tagger.py#L11-L12

**Comment by billdry** [comment]
This comment was removed in the latest commit.

**Comment by billdry** [comment]
I made the fix described in my previous comment on this issue, made the commit to this repo & will now close this issue.
