### ISSUE TITLE
[code quality] Unclear comment

### ISSUE THREAD

**Issue by ilyash-b** [aws-samples/resource-auto-tagger#4]
https://github.com/aws-samples/resource-auto-tagger/blob/8b7f0f5acb6905536dd2e24cc692db11ae970bfa/source/resource-auto-tagger.py#L19-L23

> uncompressed

As opposed to what? Where was it compressed?

> Event data for parsing API calls

What does that mean?

**Comment by billdry** [comment]
This code comment & function <get_unc_cw_event_data> are no longer required and both are removed from the script in the latest commit.

**Comment by billdry** [comment]
I made the fix described in my previous comment on this issue, made the commit to this repo & will now close this issue.
