### ISSUE TITLE
[code quality] Setting a variable followed by setting the same variable (multiple times)

### ISSUE THREAD

**Issue by ilyash-b** [aws-samples/resource-auto-tagger#5]
https://github.com/aws-samples/resource-auto-tagger/blob/8b7f0f5acb6905536dd2e24cc692db11ae970bfa/source/resource-auto-tagger.py#L21-L22

My IDE gives me this warning:

> Local variable 'cw_data_dict' value is not used.

Here and in other places, a variable is set and then set to something else on next line. The first value of the variable is not used. I highly recommend using an IDE which warns about this.

**Comment by billdry** [comment]
This variable setting then "resetting" the same variable is addressed and removed in the latest commit.

**Comment by billdry** [comment]
I made the fix described in my previous comment on this issue, made the commit to this repo & will now close this issue.
