### ISSUE TITLE
[code quality] Variable is set and only used once on next line (at least twice)

### ISSUE THREAD

**Issue by ilyash-b** [aws-samples/resource-auto-tagger#6]
https://github.com/aws-samples/resource-auto-tagger/blob/8b7f0f5acb6905536dd2e24cc692db11ae970bfa/source/resource-auto-tagger.py#L22-L23

`cw_data_dict` could be inlined: `return event['detail']`

**Comment by ilyash-b** [comment]
Second place: https://github.com/aws-samples/resource-auto-tagger/blob/8b7f0f5acb6905536dd2e24cc692db11ae970bfa/source/resource-auto-tagger.py#L37-L38

**Comment by billdry** [comment]
Setting a variable then immediately returning that variable is addressed and removed in the latest commit.

**Comment by billdry** [comment]
I made the fix described in my previous comment on this issue, made the commit to this repo & will now close this issue.
