### ISSUE TITLE
[code quality] Useless function get_unc_cw_event_data()

### ISSUE THREAD

**Issue by ilyash-b** [aws-samples/resource-auto-tagger#7]
https://github.com/aws-samples/resource-auto-tagger/blob/8b7f0f5acb6905536dd2e24cc692db11ae970bfa/source/resource-auto-tagger.py#L20-L23

`data_dict = get_unc_cw_event_data(event)` could be just `data_dict = event['detail']`

**Comment by billdry** [comment]
This function <get_unc_cw_event_data> is no longer required and removed from the script in the latest commit.

**Comment by billdry** [comment]
I made the fix described in my previous comment on this issue, made the commit to this repo & will now close this issue.
