### ISSUE TITLE
[probable code quality issue] Useless defensive coding

### ISSUE THREAD

**Issue by ilyash-b** [aws-samples/resource-auto-tagger#9]
https://github.com/aws-samples/resource-auto-tagger/blob/8b7f0f5acb6905536dd2e24cc692db11ae970bfa/source/resource-auto-tagger.py#L70

In which situation `set_resource_tags()` would get resource id which is not referring to an instance? It comes from responseElements.instancesSet.items[].instanceId. How it can be not an instance?

**Comment by billdry** [comment]
This AWS EC2 instance ID validation check was removed in the latest commit.

**Comment by billdry** [comment]
I made the fix described in my previous comment on this issue, made the commit to this repo & will now close this issue.
